# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3305bfb8689b1911d0344a26cbc79631c1b2f75f75c0d4acd4b9f3a330e8cd7f6b52c37d7ba0d9cdbbd174d5ea581997f3abaefd3325a4c0b1cf735d6e5428a0

test:
  secret_key_base: a7d5bda4c1f86fe8f8030f98f6a00c876da6413a8a5e74e3e39cea0f25889f5b5f6bda921c6627b31db6289b04b41a49c30fd9d2e43560cdbb92af217df46f49

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
